module.exports = {
  content: [
    "./backend/app/templates/admin/**/*.html",
    "./backend/app/static/js/admin_tables.js",
    "./backend/app/static/js/mobile_shell.js",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: "#eef2ff",
          100: "#e0e7ff",
          200: "#c7d2fe",
          500: "#6b74f0",
          600: "#5d67df",
          700: "#4b56c9",
        },
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        display: ["Be Vietnam Pro", "sans-serif"],
        mono: ["IBM Plex Mono", "monospace"],
      },
    },
  },
  safelist: [
    "hidden",
    "pointer-events-none",
    "opacity-60",
    "bg-slate-50",
    "text-slate-500",
    "border",
    "border-emerald-200",
    "border-indigo-200",
    "border-cyan-200",
    "border-orange-200",
    "border-rose-200",
    "border-sky-200",
    "border-amber-200",
    "border-brand-200",
    "bg-emerald-50",
    "bg-indigo-50",
    "bg-cyan-50",
    "bg-orange-50",
    "bg-rose-50",
    "bg-sky-50",
    "bg-amber-50",
    "bg-cyan-500",
    "bg-orange-500",
    "bg-indigo-500",
    "bg-sky-400",
    "bg-sky-500",
    "bg-rose-400",
    "bg-slate-300",
    "text-emerald-800",
    "text-emerald-700",
    "text-indigo-700",
    "text-indigo-600",
    "text-cyan-700",
    "text-cyan-600",
    "text-orange-700",
    "text-rose-800",
    "text-rose-700",
    "text-rose-600",
    "text-sky-800",
    "text-sky-700",
    "text-sky-600",
    "text-amber-800",
    "text-amber-700",
    "text-amber-600",
    "text-brand-700",
  ],
};
